<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>A Study in Disaster</title>
  <meta name="description" content="This project aims to come up with a multiple linear regression model to predict the survival status of passengers on the Titanic.">
  <meta name="generator" content="bookdown 0.5.10 and GitBook 2.6.7">

  <meta property="og:title" content="A Study in Disaster" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="This project aims to come up with a multiple linear regression model to predict the survival status of passengers on the Titanic." />
  <meta name="github-repo" content="blacksteed232/aStudyInDisaster" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="A Study in Disaster" />
  
  <meta name="twitter:description" content="This project aims to come up with a multiple linear regression model to predict the survival status of passengers on the Titanic." />
  

<meta name="author" content="mauveSushi">


<meta name="date" content="2017-12-11">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="method.html">
<link rel="next" href="conclusion.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />










<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Abstract</a></li>
<li class="chapter" data-level="" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i>Introduction</a></li>
<li class="chapter" data-level="1" data-path="data-explore.html"><a href="data-explore.html"><i class="fa fa-check"></i><b>1</b> Data Exploration</a><ul>
<li class="chapter" data-level="1.1" data-path="data-explore.html"><a href="data-explore.html#summary"><i class="fa fa-check"></i><b>1.1</b> Summary</a></li>
<li class="chapter" data-level="1.2" data-path="data-explore.html"><a href="data-explore.html#variable-selection"><i class="fa fa-check"></i><b>1.2</b> Variable Selection</a></li>
<li class="chapter" data-level="1.3" data-path="data-explore.html"><a href="data-explore.html#data-preparation"><i class="fa fa-check"></i><b>1.3</b> Data Preparation</a></li>
<li class="chapter" data-level="1.4" data-path="data-explore.html"><a href="data-explore.html#final-data-set-summary"><i class="fa fa-check"></i><b>1.4</b> Final Data Set Summary</a></li>
<li class="chapter" data-level="1.5" data-path="data-explore.html"><a href="data-explore.html#correlation-investigation"><i class="fa fa-check"></i><b>1.5</b> Correlation Investigation</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="method.html"><a href="method.html"><i class="fa fa-check"></i><b>2</b> Methodology</a><ul>
<li class="chapter" data-level="2.1" data-path="method.html"><a href="method.html#backward-selection"><i class="fa fa-check"></i><b>2.1</b> Backward Selection</a></li>
<li class="chapter" data-level="2.2" data-path="method.html"><a href="method.html#logistic-regression"><i class="fa fa-check"></i><b>2.2</b> Logistic Regression</a></li>
<li class="chapter" data-level="2.3" data-path="method.html"><a href="method.html#homser-lemeshow-goodness-of-fit-test"><i class="fa fa-check"></i><b>2.3</b> Homser-Lemeshow goodness-of-fit test</a></li>
<li class="chapter" data-level="2.4" data-path="method.html"><a href="method.html#akaike-information-criterion-aic"><i class="fa fa-check"></i><b>2.4</b> Akaike Information Criterion (AIC)</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="model.html"><a href="model.html"><i class="fa fa-check"></i><b>3</b> Model</a><ul>
<li class="chapter" data-level="3.1" data-path="model.html"><a href="model.html#model-obtained-using-backward-selection"><i class="fa fa-check"></i><b>3.1</b> Model obtained using backward selection</a></li>
<li class="chapter" data-level="3.2" data-path="model.html"><a href="model.html#the-final-models"><i class="fa fa-check"></i><b>3.2</b> The Final Models</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="conclusion.html"><a href="conclusion.html"><i class="fa fa-check"></i><b>4</b> Conclusion</a><ul>
<li class="chapter" data-level="4.1" data-path="conclusion.html"><a href="conclusion.html#findings"><i class="fa fa-check"></i><b>4.1</b> Findings</a></li>
<li class="chapter" data-level="4.2" data-path="conclusion.html"><a href="conclusion.html#further-study"><i class="fa fa-check"></i><b>4.2</b> Further Study</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Study in Disaster</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="model" class="section level1">
<h1><span class="header-section-number">Section 3</span> Model</h1>
<div id="model-obtained-using-backward-selection" class="section level2">
<h2><span class="header-section-number">3.1</span> Model obtained using backward selection</h2>
<p>The first model we obtained is by backward selection. We eliminated <code>number_of_siblings_and_spouses</code> and <code>fares</code> before we obtained a model whose p-value of each variable is smaller than 0.05. The model we obtained and its summary are shown below:</p>
<pre><code>## 
## Call:
## glm(formula = has_survived ~ gender + age + number_of_siblings_and_spouses + 
##     passenger_class + embarked_from, family = binomial(link = &quot;logit&quot;), 
##     data = titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.7755  -0.6791  -0.4560   0.7074   2.5697  
## 
## Coefficients:
##                                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                     4.86097    0.47163  10.307  &lt; 2e-16 ***
## gendermale                     -2.60736    0.15798 -16.505  &lt; 2e-16 ***
## age[19,55]                     -2.00712    0.38995  -5.147 2.65e-07 ***
## age[56, above)                 -3.10763    0.53229  -5.838 5.27e-09 ***
## age[6,18]                      -1.76429    0.43159  -4.088 4.35e-05 ***
## agemissing                     -2.21886    0.42028  -5.280 1.30e-07 ***
## number_of_siblings_and_spouses -0.35361    0.09297  -3.803 0.000143 ***
## passenger_classsecond          -0.91904    0.21489  -4.277 1.90e-05 ***
## passenger_classthird           -1.77251    0.19438  -9.119  &lt; 2e-16 ***
## embarked_fromQ                 -0.47350    0.30504  -1.552 0.120601    
## embarked_fromS                 -0.67719    0.18791  -3.604 0.000314 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1736.2  on 1305  degrees of freedom
## Residual deviance: 1191.1  on 1295  degrees of freedom
## AIC: 1213.1
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>As can be seen from the summary, each variable has a p-value that is much lower than 0.05 except <code>emabrked_fromQ</code>. However, since the p-value of <code>emabrked_fromS</code> is low enough, we do not need to eliminate <code>embarked_from</code> variable. Also, there is no huge change of coefficients while we eliminate <code>number_of_siblings_and_spouses</code> and <code>fares</code>, so we do not need to worry about collinearity for these two variables. (Otherwise, we have to study whether the low p-value is caused by collinearity). The formula of this model is <span class="math display">\[\hat{\frac{p}{1-\hat{p}}}= 4.86097 - 2.60736 \times gendermale -2.00712 \times age[19,55] -3.10763 \times age[56, above) -1.76429 \times age[6,18] -2.21886\times agemissing\\ -0.35361 \times number\_of\_siblings\_and\_spouses -0.91904\times passenger\_classsecond -1.77251\times passenger\_classthird\\ -0.47350\times embarked\_fromQ -0.67719\times embarked\_fromS\]</span>. Now, we shall evaluate this model using Hosmer–Lemeshow goodness-of-fit test, and the outcome is as shown below:</p>
<pre><code>## 
##  Hosmer and Lemeshow goodness of fit (GOF) test
## 
## data:  titanic$has_survived, fitted(m_best)
## X-squared = 22.308, df = 6, p-value = 0.001065</code></pre>
<p>The p-value is 0.001065, which is much lower than 0.05, and this suggests that this model is very likely to have a lack of fit. Hence, backward selection may not be the best way to fit this model, and we should find a better alternative of this model.</p>
</div>
<div id="the-final-models" class="section level2">
<h2><span class="header-section-number">3.2</span> The Final Models</h2>
<p>To get our final model, we first checked the skeptical correlations we mentioned in the Data Exploration section. First, we are going to check the correlation of gender with other variables, and we can use the plots below to see it:</p>
<p><img src="report_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>It seems that there is not a significant correlation between <code>age</code> and <code>gender</code>, or <code>embarked_from</code> and <code>gender</code>. There is a significant difference in the proportion of each passenger classes in each gender. The number of siblings and spouses also seems to be correlated with gender. Because of this, we considered making two models, one with <code>gender</code> and one without <code>gender</code>. Also, we looked at the correlation of <code>embarked_from</code> and <code>passenger_class</code>, and the plot is as shown below: <img src="report_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>As can be seen from this graph, there is a very significant correlation between <code>passenger_class</code> and <code>embarked_from</code>. For example, more than half of the passengers from Cherbourg are first class passengers, and only a few from Queenstown are first class. This suggests that we should be very careful when include both <code>passenger_class</code> and <code>embarked_from</code> in the same model.</p>
<p>Then, we created the following models. The one without <code>gender</code> takes <code>passenger_class</code>, <code>age</code> and <code>number_of_siblings_and_spouses</code> into account. We tried several models, and although we will get a better p-value from Hosmer–Lemeshow goodness-of-fit test by adding <code>embarked_from</code>, we still think it may be problematic because of its correlation with <code>passenger_class</code>. The summary of the model and the result from Hosmer–Lemeshow goodness-of-fit test is as shown:</p>
<pre><code>## 
## Call:
## glm(formula = has_survived ~ passenger_class + age + number_of_siblings_and_spouses, 
##     family = binomial(link = &quot;logit&quot;), data = titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.1791  -0.8806  -0.7015   0.9754   2.1284  
## 
## Coefficients:
##                                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                     2.43417    0.35008   6.953 3.57e-12 ***
## passenger_classsecond          -0.97894    0.17462  -5.606 2.07e-08 ***
## passenger_classthird           -1.78063    0.15635 -11.389  &lt; 2e-16 ***
## age[19,55]                     -1.78069    0.32160  -5.537 3.08e-08 ***
## age[56, above)                 -2.80888    0.44150  -6.362 1.99e-10 ***
## age[6,18]                      -1.24306    0.34932  -3.558 0.000373 ***
## agemissing                     -1.93037    0.34351  -5.620 1.91e-08 ***
## number_of_siblings_and_spouses -0.15772    0.07244  -2.177 0.029468 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1736.2  on 1305  degrees of freedom
## Residual deviance: 1557.0  on 1298  degrees of freedom
## AIC: 1573
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<pre><code>## 
##  Hosmer and Lemeshow goodness of fit (GOF) test
## 
## data:  titanic$has_survived, fitted(m_best_8)
## X-squared = 9.1521, df = 6, p-value = 0.1652</code></pre>
<p>As we mentioned before, this p-value is not the best, but this is good enough given that it is larger than 0.05. The negative coefficients of all variables suggest that the reference group is the luckiest group. That is, children (age smaller than 5) in first class without any siblings and spouses are the most likely to survive, and their natural log of odds is 2.43. This means that their chance of survival is approximately 0.9190865. This model also suggests the influence of any variable. For example, this model suggests that people in the first class is expected to have a 0.98 higher natural log of odds than people in the second class holding other variables constant. Also, we can expect a decrease of 0.16 in natural log of odds for one more increase in number of siblings and spouses.</p>
<p>This model seems good and it matches with our instinct that children and passengers in the first class will have better chance of survival in a shipwreck. However, since <code>gender</code> is such an important variable, we would like to examine a model with <code>gender</code> as an explanatory variable. We made a set of models and compared them according to their meanings and their results from Hosmer–Lemeshow goodness-of-fit test. It turns out that all the model with <code>gender</code> variable fails the Hosmer–Lemeshow goodness-of-fit test, but arguably, we find the best model which takes <code>gender</code>, <code>age</code>, <code>passenger_class</code>, and <code>number_of_siblings_and_spouses</code> because it contains the most information, and the AIC is the lowest among all the models with <code>gender</code> variable. The summary of this model is as shown below:</p>
<pre><code>## 
## Call:
## glm(formula = has_survived ~ gender + age + number_of_siblings_and_spouses + 
##     passenger_class, family = binomial(link = &quot;logit&quot;), data = titanic)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.8653  -0.6894  -0.4535   0.6856   2.5462  
## 
## Coefficients:
##                                Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                     4.46068    0.44952   9.923  &lt; 2e-16 ***
## gendermale                     -2.61030    0.15445 -16.901  &lt; 2e-16 ***
## age[19,55]                     -2.01284    0.38663  -5.206 1.93e-07 ***
## age[56, above)                 -3.08942    0.52946  -5.835 5.38e-09 ***
## age[6,18]                      -1.70756    0.42644  -4.004 6.22e-05 ***
## agemissing                     -2.15090    0.41233  -5.217 1.82e-07 ***
## number_of_siblings_and_spouses -0.37239    0.09176  -4.058 4.95e-05 ***
## passenger_classsecond          -1.11954    0.20723  -5.402 6.57e-08 ***
## passenger_classthird           -1.92213    0.18536 -10.369  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 1736.2  on 1305  degrees of freedom
## Residual deviance: 1204.1  on 1297  degrees of freedom
## AIC: 1222.1
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<pre><code>##                   y0  y1     yhat0      yhat1
## [0.00548,0.0977] 195  22 199.42682  17.573180
## (0.0977,0.111]   205  42 219.77092  27.229080
## (0.111,0.144]     26   6  27.56544   4.434556
## (0.144,0.225]    148  18 132.71261  33.287390
## (0.225,0.459]    122  63 109.91946  75.080540
## (0.459,0.628]     81  87  70.01437  97.985627
## (0.628,0.798]     21 108  32.54474  96.455263
## (0.798,0.984]     10 152  16.04564 145.954365</code></pre>
<p>As we can see from the summary, all the coefficients are negative, so the reference group is expected to be the luckiest people as is in the previous model. That is, natrual log of odds of little girls (age under 5) in first class without siblings and spouses is expected to be 4.46, which means that their chance of survival is approximately 0.9885698. Also, the coefficients suggest how each variable affect the chance of survival. For example, males are expected to have a 2.61 lower natural log of odds than females holding other variables constant. We can also see that one more siblings or spouses is associated with 0.37 decrease natural log of odds.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="method.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusion.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": false,
"fontsettings": {
"theme": "white",
"family": "Serif",
"size": 2
},
"edit": {
"link": "https://github.com/blacksteed232/aStudyInDisaster/edit/master/src/report/3-model.Rmd",
"text": "Edit"
},
"download": ["report.pdf"],
"toc": {
"collapse": "subsection",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
